### ISSUE TITLE
Merge forks

### ISSUE THREAD

**Issue by ghost** [falcondai/python-snowflake#5]
@fenhl, I also have <a href="https://github.com/Learnloot/python-snowflake-2">a fork</a> of this repository. Would you like to merge our forks so that we can work on creating a good Python snowflake tool together?

**Comment by fenhl** [comment]
My fork was only for #2 and for [`melt`](https://github.com/fenhl/melt) which I have since ported to Rust. I'm not currently interested in maintaining a library like this one.

**Comment by ghost** [comment]
Ah, ok. Thanks for considering then.
